name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
      - name: Check code style
        run: npm run lint
  test:
    name: Tests
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        react-version: [17.x, 18.x]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: npm install
      - name: Install React ${{matrix.react-version}}
        if: matrix.react-version != '18.x'
        run: |
          npm install --force --save-dev \
            react@${{matrix.react-version}} \
            react-dom@${{matrix.react-version}} \
            react-test-renderer@${{matrix.react-version}}
      - name: Run tests
        run: npm run tests-only
      - name: Submit coverage
        if: matrix.node-version == '20.x' && matrix.react-version == '18.x'
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
